name=zonemirror
service=whostmgr
url=/cgi/zonemirror/index.cgi
url2=/cgi/zonemirror/index.live.php
acls=any
target=_self
entryurl=zonemirror/index.cgi
displayname=ZoneMirror
icon=zonemirror.png
user=root
